version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
          reusable: false
      - run : |
          docker version
          docker info
      - run:
          name: unittest
          command: |
            make unittest
  black:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
          reusable: false
      - run:
          name: check format
          command: |
            make check_black
   mypy:
     docker:
       - image: circleci/python:3.6
     working_directory: ~/project
     steps:
       - checkout
       - setup_remote_docker:
          version: 18.05.0-ce
          reusable: false
       - run:
           name: run mypy
           command: |
             make mypy

workflows:
  version: 2
  build:
    jobs:
      - black
      - test
